# Generated by Django 3.2 on 2021-04-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='sort_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
