# Generated by Django 3.2 on 2021-04-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_banner_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
